### ISSUE TITLE
COOK_000C Setup project: Spring Boot

### ISSUE THREAD

**Issue by tobiasrieger** [sw20-tug/ASD-Morning-7#19]
Initialize the back end application (Spring Boot). To do so, the following [guide ](https://spring.io/guides/gs/spring-boot/) can be used.

**Comment by prdngr** [comment]
I would suggest the following [Spring Boot configuration](https://start.spring.io/#!type=maven-project&language=java&platformVersion=2.2.5.RELEASE&packaging=jar&jvmVersion=13&groupId=at.tugraz.asdmorning7&artifactId=cook&name=cook&description=&packageName=at.tugraz.asdmorning7.cook&dependencies=web,data-jpa,mysql).

**Comment by pegru** [comment]
I agree on your setup. Which java version are we supposed to support at least?

**Comment by prdngr** [comment]
> Which java version are we supposed to support at least?

Since this is a completely new project we could go for JDK 13.
